spring:
  cloud:
    gateway:
      globalcors:
         corsConfigurations:
            '[/**]':
              allowedOrigins: "localhost:4200"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders:
                - "*"
              allowCredentials: true