spring:
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
        - id: route2
          uri: http://localhost:8082
          predicates:
            - Path=/api/**